# Generated by Django 4.1.5 on 2023-02-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_alter_contact_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
