# Generated by Django 4.1.5 on 2023-02-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontent",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
