# Generated by Django 4.1.5 on 2023-02-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontent",
            name="article",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcontent",
                to="article.article",
            ),
        ),
        migrations.AlterField(
            model_name="subcontent",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="subcontentimage",
            name="subcontent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcontentimage",
                to="article.subcontent",
            ),
        ),
    ]
